TEACHER_ENCODER_INPUT_DIM = 2048
TEACHER_ENCODER_HIDDEN_1 = 1024
TEACHER_ENCODER_HIDDEN_2 = 768
TEACHER_ENCODER_OUTPUT_DIM = 512
TEACHER_TRANSFORMER_NHEAD = 8
TEACHER_TRANSFORMER_DIM_FEEDFORWARD = 2048
TEACHER_TRANSFORMER_NUM_LAYERS = 6
TEACHER_ACTION_DIM = 7
TEACHER_DROPOUT = 0.1

STUDENT_INPUT_DIM = 2048
STUDENT_MIN_HIDDEN_DIM = 128
STUDENT_ACTION_DIM = 14
STUDENT_MIN_LAYERS = 2
STUDENT_MIN_HEADS = 4
